# Generated by Django 3.0.1 on 2020-01-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_bash', models.CharField(max_length=45)),
                ('type_beer', models.CharField(max_length=45)),
                ('capacity', models.IntegerField()),
                ('liters_now', models.IntegerField()),
            ],
            options={
                'db_table': 'bash',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('contact_number', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('working_hours', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=191)),
                ('address', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('quantity', models.CharField(max_length=45)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'inputs',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
                ('contact_number', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_quantity', models.IntegerField()),
                ('input_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cerveceria.Inputs')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateTimeField()),
                ('type_beer', models.CharField(max_length=45)),
                ('liters', models.IntegerField()),
                ('folio', models.IntegerField()),
                ('additional_info', models.CharField(max_length=200)),
                ('package', models.CharField(max_length=45)),
                ('bash_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cerveceria.Bash')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cerveceria.Clients')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='CheckIns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateTimeField()),
                ('total_quantity', models.IntegerField()),
                ('input_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cerveceria.Inputs')),
            ],
            options={
                'db_table': 'check_ins',
            },
        ),
    ]
