# Generated by Django 3.0.1 on 2020-01-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveceria', '0002_auto_20200111_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='type_beer',
            field=models.CharField(max_length=45),
        ),
    ]
