# Generated by Django 3.0.1 on 2020-01-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveceria', '0005_auto_20200111_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='package',
            field=models.CharField(choices=[('b10', 'Barril de 10 litros'), ('b30', 'Barril de 30 litros'), ('b50', 'Barril de 50 litros'), ('blt', 'Botella de litro cangrejo'), ('g19', 'Growler de 1.9'), ('330', 'Botella 330'), ('ltr', 'Litro recarga')], default='b10', max_length=3),
        ),
    ]
