# Generated by Django 3.0.1 on 2020-01-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveceria', '0007_auto_20200115_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bash',
            name='capacity',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bash',
            name='liters_now',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='liters',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
