# Generated by Django 3.0.1 on 2020-01-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveceria', '0008_auto_20200115_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='mail',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
