# Generated by Django 3.0.1 on 2020-01-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveceria', '0009_clients_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bash',
            name='folio',
            field=models.IntegerField(default=0),
        ),
    ]
